### ISSUE TITLE
Attempting to run solenopsis from within cygwin produces an ant error

### ISSUE THREAD

**Issue by jayce1996** [solenopsis/Solenopsis#184] opened 2015-07-27 13:52 UTC
$ solenopsis git-push
Could not import "beatbox" library
Error: Could not find or load main class org.apache.tools.ant.Main

**Comment by sfloess** [comment] 2015-07-27 13:56
Also need to check the overall sanity of Solenopsis running under cygwin.

**Comment by sfloess** [comment] 2015-08-03 12:52
Steps to try:
* Download Ant Zip file
* Unzip Ant (for install)
* Run install script (not sure what this is yet)

**Comment by sfloess** [comment] 2015-08-03 16:26
This is a tough problem to solve and would require a new bsolenopsis.bat to work.  The problem is cygwin rightfully converts directories.  So, for example if you installed solenopsis src in c:\solenopsis, when bsolenopsis runs it see that as /cygdrive/c/solenopsis.  Unfortunately it then computes the classpath based upon /cydrive/c/solenopsis and presents that to java.  Under Windows, java has no idea where /cygrive/c/solenopsis is located yielding the reported error.

I wish I had the time to work on this, but I'm spread way to thin to take on a Windows bat project (that and I'm not versed in bat files to even consider at this point in time).

I am closing - but will gladly take a contribution should you so choose to write it :)

**Comment by sfloess** [comment] 2015-08-06 00:40
Re-opening as I closed this prematurely.  A fix is forthcoming!

**Comment by sfloess** [comment] 2015-08-06 00:41
@jayce1996 - please see last comment!

**Closed** 2015-08-06 00:47 UTC
Labels: Ant, bug, enhancement

**Comment by sfloess** [comment] 2015-08-06 00:57
@jayce1996 - checkout https://github.com/solenopsis/Solenopsis/wiki/1.1-Cygwin

**Comment by sfloess** [comment] 2018-02-17 20:26
@tdalbo92 - always feel free to open/re-open my friend...
